set shell := ["nu", "-c"]
set positional-arguments

deploy: clean create_dir copy rsync

clean:
    cd {{justfile_directory()}}; rm -rf deploy

create_dir:
    cd {{justfile_directory()}}; mkdir deploy

copy:
    #!/usr/bin/env nu
    cd {{justfile_directory()}}
    cp main.py deploy/
    cp neopixel.py deploy/
    cp display.py deploy/
    cp board.py deploy/

rsync:
    cd {{justfile_directory()}}; rshell --quiet rsync -m deploy/ /pico
